language: java
jdk: oraclejdk8
notifications:
  email:
    recipients:
      - luisvaley@hotmail.com
      - lst24@hotmail.com
    on_success: always # defaul: change
    on_failure: always # default: always
